# Generated by Django 5.2.5 on 2026-02-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bono_puntualidad', models.FloatField(default=0.0)),
                ('pago_hora_extra', models.FloatField(default=0.0)),
                ('descuento_retardo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('sueldo_base', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('entrada', models.TimeField(blank=True, null=True)),
                ('salida', models.TimeField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=50, null=True)),
                ('horas', models.FloatField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Sistema_Momias.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('sueldo_base', models.FloatField()),
                ('horas_extra', models.FloatField(default=0.0)),
                ('incidencias', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sistema_Momias.empleado')),
            ],
        ),
    ]
