# Generated by Django 5.2.5 on 2026-02-25 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estatus',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='TEMP', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='empleados/pdfs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Sistema_Momias.empleado')),
            ],
        ),
    ]
