# Generated by Django 5.2.5 on 2026-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0002_empleado_estatus_empleado_fecha_baja_empleado_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/empleados/fotos/'),
        ),
    ]
