# Generated by Django 5.2.5 on 2026-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0003_alter_empleado_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='bonificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
