# Generated by Django 5.2.5 on 2026-02-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0004_asistencia_bonificacion_asistencia_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
