# Generated by Django 5.2.5 on 2026-02-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0005_asistencia_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='salida_matutina',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='salida_vespertina',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
