# Generated by Django 5.2.5 on 2026-02-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema_Momias', '0006_asistencia_salida_matutina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='retardo',
            field=models.IntegerField(default=0),
        ),
    ]
